# Generated by Django 3.2.9 on 2021-11-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_rename_head_image_post_upload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_file',
            field=models.FileField(blank=True, upload_to='blog/files/%Y/%m/%d'),
        ),
    ]
